### PR TITLE
Simplify secret name referencing, and move SMTP URL to secret

### LINKED ISSUE #3: bluesky-pds: Move SMTP URL to secrets?
The SMTP URL can include the password, I'd like to separate that out into a secret instead.

### PR DESCRIPTION
**Pull request by nogweii**
Closes #3 . This is backwards-incompatible though, I can add that if you want to.

### CODE REVIEW

**Comment by Nerkho** [comment]
Thanks a lot @nogweii. I like it. :)

As far as I understand, the only part that is backwards-incompatible would be the `pdsEmailSmtpUrl` or am I missing something?

**Comment by nogweii** [comment]
Yeah, sorry for not making it clearer. Only `pdsEmailSmtpUrl` would be affected.

**Comment by Nerkho** [comment]
> Yeah, sorry for not making it clearer. Only `pdsEmailSmtpUrl` would be affected.

No worries, :) just wanted to make sure.

~~Can I ask you to squash your commits into one? I'll merge the pr afterward.~~ nevermind

**Review by Nerkho — APPROVED** [review]
lgtm

**Pull request merged**
